Development (#20)
* >> appends to the file, or creates it if unexistent. This is a cleaner solution.

* Quote some variables. Exit early on failed checks.

* Update error reporting format.

* added the '-r' flag to runch. issue #19.

* formatting.

* added a license.

* formatting.

* standarized formatting for everything.

diff --git a/copier b/copier
--- a/copier
+++ b/copier
@@ -1,42 +1,38 @@
 #! /bin/sh
 
 
+set -e
+_e () { printf "${0##*/}: \e[31mError:\e[0m %s\n" "$*" >&2; exit 1; }
+
 case "$1" in
-
 	-h|--help)
+		printf "%s\n" \
+			"${0##*/}: copy binaries and their dependencies to a directory." \
+			"" \
+			"usage:" \
+			"  ${0##*/} [-h|--help]  show this help." \
+			"  ${0##*/} <dir> <bins>" \
 
-		echo "${0##*/}: Copy binaries and their dependencies to a directory."
-		echo "Usage: ${0##*/} [-h|--help] <directory> <binaries>"
 		exit
-
 	;;
 
 	-d|--debug)
-
 		set -x
 		shift
-
 	;;
-
 esac
 
-_e () { echo -e "${0##*/}: \e[31mError:\e[0m $@" >&2; exit 1; }
 
-
-
-
-#		Check the command line.
+#	check the command line.
 
 test $# -lt 2 &&
-	_e "Too few arguments."
+	_e "too few arguments."
 
 dst="$1"
 shift
 
 
-
-
-#		Check if arguments are files.
+#	check if arguments are files.
 
 for f in "$@"; do
 	test -f "$f" ||
@@ -44,15 +40,13 @@ for f in "$@"; do
 done
 
 
-
-
-#		Copy the binaries.
+#	copy the binaries.
 
 for f in "$@"; do
 	mkdir -p "$dst/${f%/*}"
 	cp -u "$f" "$dst/$f"
 
-	#	Copy the libraries.
+	#	copy the libraries.
 
 	ldd "$f"         |
 	cut -d " " -f 3  |
@@ -62,7 +56,7 @@ for f in "$@"; do
 	sort -u          |
 	while read l; do
 		test -f "$l" ||
-			_e "Missing dependency of '$f': '$l'."
+			_e "missing dependency of '$f': '$l'."
 
 		mkdir -p "$dst/${l%/*}"
 		cp -u "$l" "$dst/$l"
diff --git a/mkiso b/mkiso
--- a/mkiso
+++ b/mkiso
@@ -2,17 +2,13 @@
 
 
 set -e
-
-_e () { echo -e "${0##*/}: \e[31mError:\e[0m $@" >&2; exit 1; }
-
+_e () { printf "${0##*/}: \e[31mError:\e[0m %s\n" "$*" >&2; exit 1; }
 
 
-
-#		Option parsing.
+#	option parsing.
 
 while :; do
 	case "$1" in
-
 		-V)
 			label=$2
 			shift 2
@@ -59,33 +55,33 @@ while :; do
 		;;
 
 		-h|--help)
-			echo "${0##*/}: Generate an ISO image from a directory."
-			echo "Usage: ${0##*/} [flags]  <directory> <output>"
-			echo
-			echo "-h, --help       Show this help. "
-			echo "-d, --debug      Enable debugging messages."
-			echo "-b               Enable BIOS support."
-			echo "-e               Enable UEFI support."
-			echo "-V <label>       Set the filesystem label to <label>."
-			echo "-g <file>        Use <file> as a GRUB configuration file."
-			echo "-t <path>        Use <path> as a GRUB theme."
-			echo "-u <update_url>  For use with znx."
-			echo "-s <hash_url>    For use with znx."
-			echo "-r <release>     For use with znx."
+			printf "%s\n" \
+				"${0##*/}: generate an ISO image." \
+				"" \
+				"usage:" \
+				"  ${0##*/} [-h|--help]  show this help." \
+				"  ${0##*/} [options] <dir> <img>" \
+				"" \
+				"options:" \
+				"  -d, --debug    enable debugging messages." \
+				"  -b             enable BIOS support." \
+				"  -e             enable UEFI support." \
+				"  -V label       use label as filesystem label." \
+				"  -g file        use file as a GRUB configuration file." \
+				"  -t path        use path as a GRUB theme." \
+				"  -u update_url  znx's update_url." \
+				"  -s hash_url    znx's hash_url." \
+				"  -r release     znx's release."
 			exit
 		;;
 
 		-*) _e "Unknown option '$1'.";;
-
 		*) break;;
-
 	esac
 done
 
 
-
-
-#		Check the command line.
+#	check the command line.
 
 iso_dir="$1"
 output="$2"
@@ -97,9 +93,7 @@ test -d "$iso_dir" ||
 	_e "'$iso_dir' is not a directory."
 
 
-
-
-#		Copy the configuration files.
+#	copy the configuration files.
 
 test "$config_files" && {
 	mkdir -p "$iso_dir"/boot/grub
@@ -107,9 +101,7 @@ test "$config_files" && {
 }
 
 
-
-
-#		Copy the themes.
+#	copy the themes.
 
 test "$themes" && {
 	mkdir -p "$iso_dir"/boot/grub/themes
@@ -117,26 +109,20 @@ test "$themes" && {
 }
 
 
-
-
-#		Create the .INFO file if needed.
+#	create the .INFO file if needed.
 
 test "$hash_url" && echo "HASH_URL $hash_url" >> "$iso_dir/.INFO"
 test "$update_url" && echo "UPDATE_URL $update_url" >> "$iso_dir/.INFO"
 test "$release" && echo "RELEASE $release" >> "$iso_dir/.INFO"
 
 
-
-
-#		GRUB2 modules.
+#	GRUB2 modules.
 
 _bios_mods="biosdisk boot linux search normal configfile part_gpt btrfs ext2 fat iso9660 loopback test keystatus gfxmenu regexp probe all_video gfxterm font echo read ls cat png jpeg halt reboot"
 _uefi_mods="efi_gop efi_uga boot linux search normal configfile part_gpt btrfs ext2 fat iso9660 loopback test keystatus gfxmenu regexp probe all_video gfxterm font echo read ls cat png jpeg halt reboot"
 
 
-
-
-#		Generate boot artifacts.
+#	generate boot artifacts.
 
 test "$bios" = y && {
 	bios_img=bios.img
@@ -195,9 +181,7 @@ test "$uefi" = y && {
 }
 
 
-
-
-#		Generate ISO image.
+#	generate ISO image.
 
 xorriso \
 	-as mkisofs \
diff --git a/pull b/pull
--- a/pull
+++ b/pull
@@ -3,24 +3,23 @@
 
 set -e
 
+_e () { printf "${0##*/}: \e[31mError:\e[0m %s\n" "$*" >&2; exit 1; }
+
+
 case "$1" in
-
 	-h|--help)
-
-		echo "${0##*/}: Pull an image from DockerHub into a directory."
-		echo "Usage: pull <directory> <image>"
+		printf "%s\n" \
+			"${0##*/}: pull an image from DockerHub into a directory." \
+			"" \
+			"usage:" \
+			"  ${0##*/} pull [-h|--help]  show this help." \
+			"  ${0##*/} pull <dir> <img>"
 		exit
-
 	;;
-
 esac
 
-_e () { echo -e "${0##*/}: \e[31mError:\e[0m $@" >&2; exit 1; }
 
-
-
-
-#   	Functions.
+#	Functions.
 
 _get_manifest () {
 	curl -f -s \
@@ -48,7 +47,6 @@ _pull_layers () {
 
 _pull () {
 	cd "$1"
-
 	_get_manifest "$2" "$3" "$4" | _pull_layers "$2" "$4"
 
 	for f in *; do
@@ -58,12 +56,10 @@ _pull () {
 }
 
 
-
-
 #   	Process the request.
 
 test $# -eq 2 ||
-	_e "Wrong number of arguments."
+	_e "wrong number of arguments."
 
 tag="${2##*:}"
 img="${2%%:*}"
@@ -71,14 +67,14 @@ owner="${img%%/*}"
 out="$1"
 
 test "$img" ||
-	_e "No image provided."
+	_e "no image provided."
 
 mkdir -p "$out"
 
 test -z "$tag" -o "$tag" = "$img" && tag=latest
 test -z "$owner" -o "$owner" = "$img" && img="library/$img"
 
-echo "Trying to pull $img:$tag"
+echo "trying to pull $img:$tag"
 
 until test "$token"; do
 	token=$(curl -sf "https://auth.docker.io/token?service=registry.docker.io&scope=repository:$img:pull" | jq -r .token)
diff --git a/runch b/runch
--- a/runch
+++ b/runch
@@ -2,15 +2,12 @@
 
 
 set -e
-
-_e () { echo -e "${0##*/}: \e[31mError:\e[0m $@" >&2; exit 1; }
-
+_e () { printf "${0##*/}: \e[31mError:\e[0m %s\n" "$*" >&2; exit 1; }
 
 
-#		Functions.
+#	functions.
 
 clean () {
-
 	umount -R -f \
 		$_chroot_dir/proc \
 		$_chroot_dir/sys \
@@ -22,17 +19,19 @@ clean () {
 		$_chroot_dir/etc/nsswitch.conf \
 		$_chroot_dir/etc/resolv.conf
 
-	#   Clean the user mount points.
+	#	clean the user mount points.
 
 	for m in $_extra_mount_points; do
 		umount -R -f $_chroot_dir/"${m##*:}"
 	done
 
+	for d in $_rm_f; do
+		rm -rf $_chroot_dir/"$d"
+	done
 }
 
 
 _mount () {
-
 	test -e "$1" ||
 		_e "'$1' does not exist."
 
@@ -42,20 +41,13 @@ _mount () {
 	test -d "$1" && mkdir -p "$2"
 
 	mount -B "$1" "$2"
-
 }
 
 
-
-
-#		Parse the command line.
+#	parse the command line.
 
 while :; do
-
 	case "$1" in
-
-		#	Mount points are given in the format: <src>:<mnt>
-
 		-m)
 			_extra_mount_points="$_extra_mount_points $2"
 			shift 2
@@ -66,29 +58,38 @@ while :; do
 			shift 2
 		;;
 
+		-r)
+			_rm="$_rm_f $2"
+			shift
+		;;
+
 		-d|--debug)
 			set -x
 			shift
 		;;
 
 		-h|--help)
-			echo "${0##*/}: Run commands in a preconfigured chroot."
-			echo "Usage: ${0##*/} [-h|--help] [-u user[:group]] [-m src:mnt] <directory> <command> [command arguments]"
+			printf "%s\n" \
+				"${0##*/}: run commands in a preconfigured chroot." \
+				"" \
+				"usage:" \
+				"  ${0##*/} [-h|--help]  show this help." \
+				"  ${0##*/} [options] <dir> <cmd> [args]" \
+				"" \
+				"options:" \
+				"  -u user[:group]  run <cmd> as the specified user and group id." \
+				"  -m src:mnt       mount src into <dir>/mnt." \
+				"  -r file          remove file from <dir> when <cmd> finishes."
 			exit
 		;;
 
 		-*) _e "Unknown option '$1'.";;
-
 		*) break;;
-
 	esac
-
 done
 
 
-
-
-#		Check the command line.
+#	check the command line.
 
 test $(id -u) -eq 0 ||
 	_e "This program needs root privileges to run."
@@ -100,16 +101,12 @@ _chroot_dir="$1"
 shift
 
 
-
-
-#		Clean the chroot directory on exit.
+#	clean the chroot directory on exit.
 
 trap clean EXIT HUP INT TERM
 
 
-
-
-#		Create the FHS mount points for the chroot.
+#	create the FHS mount points for the chroot.
 
 mkdir -p \
 	$_chroot_dir/proc \
@@ -127,9 +124,7 @@ mount -t tmpfs -o mode=1777,strictatime,nodev,nosuid - $_chroot_dir/tmp
 mount -B /run $_chroot_dir/run
 
 
-
-
-#		Allow network access.
+#	allow network access.
 
 mkdir -p $_chroot_dir/etc
 
@@ -140,23 +135,19 @@ for f in \
 	/etc/resolv.conf
 do
 	test -f $f && {
-		test -f $_chroot_dir/$f || > $_chroot_dir/$f
+		>> $_chroot_dir/$f
 		mount -B $f $_chroot_dir/$f
 	}
 done
 
 
-
-
-#		Mount user-specified mount points.
+#	mount user-specified mount points.
 
 for dir in $_extra_mount_points; do
 	_mount "${dir%%:*}" $_chroot_dir/"${dir##*:}"
 done
 
 
-
-
-#   Run the command in the chroot.
+#	run the chroot.
 
 chroot $_user_spec "$_chroot_dir" "$@"
diff --git a/synth b/synth
--- a/synth
+++ b/synth
@@ -1,24 +1,23 @@
 #! /bin/sh
 
 
+set -e
+_e () { printf "${0##*/}: \e[31mError:\e[0m %s\n" "$*" >&2; exit 1; }
+
 case "$1" in
-
 	-h|--help)
-
-		echo "${0##*/}: Generate the ISO image described in the given file."
-		echo "Usage: ${0##*/} <input> [output]"
+		printf "%s\n" \
+			"${0##*/}: generate the ISO image described in the given file." \
+			"" \
+			"usage:" \
+			"  ${0##*/} [-h|--help]  show this help." \
+			"  ${0##*/} <file> [img]"
 		exit
-
 	;;
-
 esac
 
-_e () { echo -e "${0##*/}: \e[31mError:\e[0m $@" >&2; exit 1; }
 
-
-
-
-#		Functions.
+#	functions.
 
 get_k () { echo "$desc" | grep "$1" | cut -d " " -f 2-; }
 
@@ -26,7 +25,7 @@ get_k () { echo "$desc" | grep "$1" | cut -d " " -f 2-; }
 setup_base () {
 	sys_base=$(get_k BASE)
 
-	case $sys_base in
+	case "$sys_base" in
 		@URL:*)
 			tmp=$(mktemp)
 			wget -qO $tmp "${sys_base#@URL:}"
@@ -34,15 +33,14 @@ setup_base () {
 		;;
 
 		@LOCAL:*) tar xf "${sys_base#@LOCAL:}" -C $tmp_root;;
-
 		*) pull $tmp_root $sys_base;;
 	esac
 
-	test -x "${input%/*}/prepare.sh" && {
-		cp "${input%/*}/prepare.sh" $tmp_root
-		runch $tmp_root /prepare.sh
-		rm -rf $tmp_root/prepare.sh
-	}
+	test -x "${input%/*}/prepare.sh" || return
+
+	cp "${input%/*}/prepare.sh" $tmp_root
+	runch $tmp_root /prepare.sh
+	rm -rf $tmp_root/prepare.sh
 }
 
 
@@ -67,36 +65,36 @@ install_pkgs () {
 		;;
 
 		"")
-			echo " :: WARNING:"
-			echo "    No package manager specified."
+			printf "%s\n" \
+				" :: warning:" \
+				"    no package manager specified."
 			return
 		;;
 
-		?*)
-			_e "Unsupported package manager '$pm'. Aborting."
-		;;
+		?*) _e "unsupported package manager '$pm'. aborting.";;
 	esac
 
 	runch $tmp_root $pm_u
 
 	test "$pkgs" || {
-		echo " :: WARNING:"
-		echo "    No additional packages were specified."
+		printf "%s\n" \
+			" :: warning:" \
+			"    no additional packages were specified."
 		return
 	}
 
 	runch $tmp_root $pm_i $pkgs
 
-	test -x "${input%/*}/finish.sh" && {
-		cp "${input%/*}/finish.sh" $tmp_root
-		runch $tmp_root /finish.sh
-		rm -rf $tmp_root/finish.sh
-	}
+	test -x "${input%/*}/finish.sh" &&
+		runch \
+			-m "${input%/*}/finish.sh":/finish.sh  \
+			-r /finish.sh \
+			$tmp_root /finish.sh
 }
 
 
 setup_bootloader () {
-	for item in $(get_k BOOT_FILES); do
+	get_k BOOT_FILES | while read item; do
 		src="$tmp_root/${item%=>*}"
 		dst="$iso_dir/${item#*=>}"
 		src_path="${src%/*}"
@@ -111,16 +109,19 @@ setup_bootloader () {
 }
 
 
-
-
-#		Setup the build.
+#	setup the build.
 
 root_sfs=rootfs.sfs
 tmp_root=$(mktemp -d $(pwd)/.tmp.XXXX)
 iso_dir=$(mktemp -d $(pwd)/.tmp.XXXX)
 
-input="$1"
-output="${2:-${1%.th}.iso}"
+input="${1:-synthfile}"
+output="${2:-${1%.synth}.iso}"
+
+
+#	remove waste after the build.
+
+trap "rm -rf $tmp_root $iso_dir" EXIT HUP INT TERM
 
 test -f "$input" ||
 	_e "'$input' is not a file."
@@ -129,15 +130,13 @@ test -e "$output" &&
 	_e "'$output' already exists."
 
 
-
-
-#		Start the build.
+#	start the build.
 
 desc=$(
 	sed -E \
 		-e ":x N" \
 		-e "/,$/ b x" \
-		-e "/[A-Z_]$/ b x" \
+		-e "/[A-Z_][ \t]*$/ b x" \
 		-e "s/,\n[ \t]*/ /g" \
 		-e "s/([A-Z_]+)\n*[ \t]*/\1 /g" \
 		-e "s/[ \t]*->[ \t]*/->/g" \
@@ -149,9 +148,7 @@ install_pkgs
 setup_bootloader
 
 
-
-
-#		All done. Generate the artifacts.
+#	all done. generate the artifacts.
 
 mksquashfs \
 	$tmp_root \
@@ -168,20 +165,21 @@ mkiso \
 	$(test $(get_k BIOS_BOOT) = on && echo "-b") \
 	$(test $(get_k UEFI_BOOT) = on && echo "-e") \
 	$iso_dir \
-	$output
+	"$output"
 
 
 zsyncmake \
-	$output \
-	-u "$(_get_k UPDATE_URL)" \
-	-o $output.zsync
+	"$output" \
+	-u "$(get_k UPDATE_URL)" \
+	-o "$output.zsync"
 
 
-sha256sum $output > $output.sha256sum
-md5sum $output > $output.md5sum
+sha256sum "$output" > "$output.sha256sum"
+md5sum "$output" > "$output.md5sum"
 
-echo "Successfully generated '$output'."
-echo "---------------------------------"
-echo ""
+printf "%s\n" \
+	"successfully generated '$output'." \
+	"---------------------------------" \
+	""
 
 ls --color -l $output*
