standarized formatting for everything.

diff --git a/copier b/copier
--- a/copier
+++ b/copier
@@ -1,8 +1,10 @@
 #! /bin/sh
 
 
-case "$1" in
+set -e
+_e () { printf "${0##*/}: \e[31mError:\e[0m %s\n" "$*" >&2; exit 1; }
 
+case "$1" in
 	-h|--help)
 		printf "%s\n" \
 			"${0##*/}: copy binaries and their dependencies to a directory." \
@@ -18,15 +20,10 @@ case "$1" in
 		set -x
 		shift
 	;;
-
 esac
 
-_e () { printf "${0##*/}: \e[31mError:\e[0m %s\n" "$@" >&2; exit 1; }
 
-
-
-
-#		Check the command line.
+#	check the command line.
 
 test $# -lt 2 &&
 	_e "too few arguments."
@@ -35,9 +32,7 @@ dst="$1"
 shift
 
 
-
-
-#		Check if arguments are files.
+#	check if arguments are files.
 
 for f in "$@"; do
 	test -f "$f" ||
@@ -45,15 +40,13 @@ for f in "$@"; do
 done
 
 
-
-
-#		Copy the binaries.
+#	copy the binaries.
 
 for f in "$@"; do
 	mkdir -p "$dst/${f%/*}"
 	cp -u "$f" "$dst/$f"
 
-	#	Copy the libraries.
+	#	copy the libraries.
 
 	ldd "$f"         |
 	cut -d " " -f 3  |
diff --git a/execs b/execs
--- a/execs
+++ b/execs
@@ -1,24 +1,24 @@
 #! /bin/sh
 
 
+set -e
+_e () { printf "${0##*/}: \e[31mError:\e[0m %s\n" "$*" >&2; exit 1; }
+
+
 case "$1" in
-
 	-h|--help)
-
-		echo "${0##*/}: Print the commands called by a UNIX shell script."
-		echo "Usage: ${0##*/} [-h|--help] <script>"
+		printf "%s\n" \
+			"${0##*/}: print the external commands called by a UNIX shell script." \
+			"" \
+			"usage:" \
+			"  ${0##*/} [-h|--help]" \
+			"  ${0##*/} <script>"
 		exit
-
 	;;
-
 esac
 
-_e () { printf "${0##*/}: \e[31mError:\e[0m %s\n" "$@" >&2; exit 1; }
 
-
-
-
-#		Functions.
+#	functions.
 
 _list_cmds () {
 	sed \
@@ -39,13 +39,15 @@ _get_path () {
 	while read f; do
 		{
 			which -- "$f" && continue
-			test -f "$f" && echo "$f"
+			test -f "$f" && printf "%s\n" "$f"
 		} || true
 	done 2> /dev/null
 }
 
 
+#	get the list.
+
 _list_cmds "$@" |
-cut -d ' ' -f 1 |
-sort -u         |
-_get_path
+	cut -d ' ' -f 1 |
+	sort -u         |
+	_get_path
diff --git a/runch b/runch
--- a/runch
+++ b/runch
@@ -2,15 +2,12 @@
 
 
 set -e
-
-_e () { printf "${0##*/}: \e[31mError:\e[0m %s\n" "$@" >&2; exit 1; }
-
+_e () { printf "${0##*/}: \e[31mError:\e[0m %s\n" "$*" >&2; exit 1; }
 
 
-#		Functions.
+#	functions.
 
 clean () {
-
 	umount -R -f \
 		$_chroot_dir/proc \
 		$_chroot_dir/sys \
@@ -22,7 +19,7 @@ clean () {
 		$_chroot_dir/etc/nsswitch.conf \
 		$_chroot_dir/etc/resolv.conf
 
-	#   Clean the user mount points.
+	#	clean the user mount points.
 
 	for m in $_extra_mount_points; do
 		umount -R -f $_chroot_dir/"${m##*:}"
@@ -35,7 +32,6 @@ clean () {
 
 
 _mount () {
-
 	test -e "$1" ||
 		_e "'$1' does not exist."
 
@@ -45,17 +41,13 @@ _mount () {
 	test -d "$1" && mkdir -p "$2"
 
 	mount -B "$1" "$2"
-
 }
 
 
-
-
-#		Parse the command line.
+#	parse the command line.
 
 while :; do
 	case "$1" in
-
 		-m)
 			_extra_mount_points="$_extra_mount_points $2"
 			shift 2
@@ -88,20 +80,16 @@ while :; do
 				"  -u user[:group]  run <cmd> as the specified user and group id." \
 				"  -m src:mnt       mount src into <dir>/mnt." \
 				"  -r file          remove file from <dir> when <cmd> finishes."
-
 			exit
 		;;
 
 		-*) _e "Unknown option '$1'.";;
 		*) break;;
-
 	esac
 done
 
 
-
-
-#		Check the command line.
+#	check the command line.
 
 test $(id -u) -eq 0 ||
 	_e "This program needs root privileges to run."
@@ -113,16 +101,12 @@ _chroot_dir="$1"
 shift
 
 
-
-
-#		Clean the chroot directory on exit.
+#	clean the chroot directory on exit.
 
 trap clean EXIT HUP INT TERM
 
 
-
-
-#		Create the FHS mount points for the chroot.
+#	create the FHS mount points for the chroot.
 
 mkdir -p \
 	$_chroot_dir/proc \
@@ -140,9 +124,7 @@ mount -t tmpfs -o mode=1777,strictatime,nodev,nosuid - $_chroot_dir/tmp
 mount -B /run $_chroot_dir/run
 
 
-
-
-#		Allow network access.
+#	allow network access.
 
 mkdir -p $_chroot_dir/etc
 
@@ -159,17 +141,13 @@ do
 done
 
 
-
-
-#		Mount user-specified mount points.
+#	mount user-specified mount points.
 
 for dir in $_extra_mount_points; do
 	_mount "${dir%%:*}" $_chroot_dir/"${dir##*:}"
 done
 
 
-
-
-#   Run the command in the chroot.
+#	run the chroot.
 
 chroot $_user_spec "$_chroot_dir" "$@"
diff --git a/synth b/synth
--- a/synth
+++ b/synth
@@ -1,24 +1,23 @@
 #! /bin/sh
 
 
+set -e
+_e () { printf "${0##*/}: \e[31mError:\e[0m %s\n" "$*" >&2; exit 1; }
+
 case "$1" in
-
 	-h|--help)
-
-		echo "${0##*/}: Generate the ISO image described in the given file."
-		echo "Usage: ${0##*/} <input> [output]"
+		printf "%s\n" \
+			"${0##*/}: generate the ISO image described in the given file." \
+			"" \
+			"usage:" \
+			"  ${0##*/} [-h|--help]  show this help." \
+			"  ${0##*/} <file> [img]"
 		exit
-
 	;;
-
 esac
 
-_e () { printf "${0##*/}: \e[31mError:\e[0m %s\n" "$@" >&2; exit 1; }
 
-
-
-
-#		Functions.
+#	functions.
 
 get_k () { echo "$desc" | grep "$1" | cut -d " " -f 2-; }
 
@@ -34,7 +33,6 @@ setup_base () {
 		;;
 
 		@LOCAL:*) tar xf "${sys_base#@LOCAL:}" -C $tmp_root;;
-
 		*) pull $tmp_root $sys_base;;
 	esac
 
@@ -67,31 +65,31 @@ install_pkgs () {
 		;;
 
 		"")
-			echo " :: WARNING:"
-			echo "    No package manager specified."
+			printf "%s\n" \
+				" :: warning:" \
+				"    no package manager specified."
 			return
 		;;
 
-		?*)
-			_e "Unsupported package manager '$pm'. Aborting."
-		;;
+		?*) _e "unsupported package manager '$pm'. aborting.";;
 	esac
 
 	runch $tmp_root $pm_u
 
 	test "$pkgs" || {
-		echo " :: WARNING:"
-		echo "    No additional packages were specified."
+		printf "%s\n" \
+			" :: warning:" \
+			"    no additional packages were specified."
 		return
 	}
 
 	runch $tmp_root $pm_i $pkgs
 
-	test -x "${input%/*}/finish.sh" || return
-
-	cp "${input%/*}/finish.sh" $tmp_root
-	runch $tmp_root /finish.sh
-	rm -rf $tmp_root/finish.sh
+	test -x "${input%/*}/finish.sh" &&
+		runch \
+			-m "${input%/*}/finish.sh":/finish.sh  \
+			-r /finish.sh \
+			$tmp_root /finish.sh
 }
 
 
@@ -111,9 +109,7 @@ setup_bootloader () {
 }
 
 
-
-
-#		Setup the build.
+#	setup the build.
 
 root_sfs=rootfs.sfs
 tmp_root=$(mktemp -d $(pwd)/.tmp.XXXX)
@@ -123,9 +119,7 @@ input="${1:-synthfile}"
 output="${2:-${1%.synth}.iso}"
 
 
-
-
-#		Remove waste after the build.
+#	remove waste after the build.
 
 trap "rm -rf $tmp_root $iso_dir" EXIT HUP INT TERM
 
@@ -136,9 +130,7 @@ test -e "$output" &&
 	_e "'$output' already exists."
 
 
-
-
-#		Start the build.
+#	start the build.
 
 desc=$(
 	sed -E \
@@ -156,9 +148,7 @@ install_pkgs
 setup_bootloader
 
 
-
-
-#		All done. Generate the artifacts.
+#	all done. generate the artifacts.
 
 mksquashfs \
 	$tmp_root \
@@ -187,8 +177,9 @@ zsyncmake \
 sha256sum "$output" > "$output.sha256sum"
 md5sum "$output" > "$output.md5sum"
 
-echo "Successfully generated '$output'."
-echo "---------------------------------"
-echo ""
+printf "%s\n" \
+	"successfully generated '$output'." \
+	"---------------------------------" \
+	""
 
 ls --color -l $output*
