updated scripts.

diff --git a/copier b/copier
--- a/copier
+++ b/copier
@@ -1,18 +1,17 @@
 #! /bin/sh
 
 
-set -e
-_e () { printf "${0##*/}: \e[31mError:\e[0m %s\n" "$*" >&2; exit 1; }
+err () { printf "${0##*/}: \e[31mError:\e[0m %s\n" "$*" >&2; exit 1; }
 
 case "$1" in
 	-h|--help)
 		printf "%s\n" \
 			"${0##*/}: copy binaries and their dependencies to a directory." \
+			"the list of binaries will be read from stdin." \
 			"" \
 			"usage:" \
 			"  ${0##*/} [-h|--help]  show this help." \
-			"  ${0##*/} <dir> <bins>" \
-
+			"  ${0##*/} <dir>"
 		exit
 	;;
 
@@ -26,7 +25,7 @@ esac
 #	check the command line.
 
 test $# -lt 2 &&
-	_e "too few arguments."
+	err "too few arguments."
 
 dst="$1"
 shift
@@ -36,7 +35,7 @@ shift
 
 for f in "$@"; do
 	test -f "$f" ||
-		_e "'$f' is not a file."
+		err "'$f' is not a file."
 done
 
 
@@ -48,15 +47,13 @@ for f in "$@"; do
 
 	#	copy the libraries.
 
-	ldd "$f"         |
-	cut -d " " -f 3  |
-	grep -v -E       \
-		-e 'dynamic' \
-		-e '(^$|:$)' |
-	sort -u          |
-	while read l; do
+	ldd "$f" \
+	| cut -d " " -f 3  \
+	| grep -vE -e 'dynamic'	-e '(^$|:$)' \
+	| sort -u \
+	| while read l; do
 		test -f "$l" ||
-			_e "missing dependency of '$f': '$l'."
+			err "missing dependency of '$f': '$l'."
 
 		mkdir -p "$dst/${l%/*}"
 		cp -u "$l" "$dst/$l"
