Updates...

diff --git a/execs b/execs
--- a/execs
+++ b/execs
@@ -1,27 +1,28 @@
 #! /bin/sh
 
 
-err () { printf "${0##*/}: \e[31merror:\e[0m %s\n" "$*" >&2; exit 1; }
-
-
 case "$1" in
-    (-h|--help)
+    ( -h | --help )
         printf "%s\n" \
-            "${0##*/}: print the external commands called by a shell script." \
+            "${0##*/}: Print the external commands called by a shell script." \
             "" \
             "usage:" \
             "  ${0##*/} [-h|--help]" \
             "  ${0##*/} <scripts>"
-        exit
-    ;;
+
+        exit;;
 esac
 
 
-#	functions.
+#   Functions.
+
+err () { printf "${0##*/}: \e[31merror:\e[0m %s\n" "$*" >&2; exit 1; }
 
 _list_cmds () {
     sed '''
         /^#/d
+        /^$/d
+        /^[ \t]*/d
         s:(:\n:g
         s:{:\n:g
         s:`:\n:g
@@ -30,11 +31,8 @@ _list_cmds () {
         s:;:\n:g
         s:exec:\n:g
         s:eval:\n:g
-        s:^[ \t]*::
-        /^$/d
     ''' "$@"
 }
-
 
 _get_path () {
     while read f; do
@@ -45,9 +43,9 @@ _get_path () {
 }
 
 
-#	get the list.
+#   Get the list.
 
 _list_cmds "$@" \
-    | awk '{ print $1 }' \
+    | awk '{print $1}' \
     | sort -u \
     | _get_path
diff --git a/mkiso b/mkiso
--- a/mkiso
+++ b/mkiso
@@ -2,75 +2,51 @@
 
 
 put () { printf "%b\n" "$@"; }
-err () { put "${0##*/}: \e[31mError:\e[0m $*" >&2; exit 1; }
+err () { put "mkiso: \e[31mError:\e[m $*" >&2; exit 1; }
 
 
-#	option parsing.
+#   option parsing.
 
 while :; do
     case "$1" in
-        (-V)
-            label="$2"
-            shift 2;;
+        ( -V )  label="$2"; shift 2;;
+        ( -g )  cfg_files="$cfg_files $2"; shift 2;;
+        ( -t )  theme="$themes $2"; shift 2;;
 
-        (-g)
-            config_files="$config_files $2"
-            shift 2;;
+        ( -u )  update_url="$2"; shift 2;;
+        ( -s )  hash_url="$2"; shift 2;;
+        ( -r )  release="$2"; shift 2;;
 
-        (-t)
-            themes="$themes $2"
-            shift 2;;
+        ( -b )  bios=y; shift;;
+        ( -e )  uefi=y; shift;;
 
-        (-u)
-            update_url="$2"
-            shift 2;;
+        ( -d | --debug )    set -x; shift;;
 
-        (-s)
-            hash_url="$2"
-            shift 2;;
-
-        (-r)
-            release="$2"
-            shift 2;;
-
-        (-b)
-            bios=y
-            shift;;
-
-        (-e)
-            uefi=y
-            shift;;
-
-        (-d|--debug)
-            set -x
-            shift;;
-
-        (-h|--help)
-            put "${0##*/}: generate an ISO image." \
-                "" \
-                "usage:" \
-                "  ${0##*/} [-h|--help] show this help." \
-                "  ${0##*/} [options] <dir> <img>" \
-                "" \
-                "options:" \
-                "  -d, --debug    enable debugging messages." \
-                "  -b             enable BIOS support." \
-                "  -e             enable UEFI support." \
-                "  -V label       use label as filesystem label." \
-                "  -g file        use file as a GRUB configuration file." \
-                "  -t path        use path as a GRUB theme." \
-                "  -u update_url  znx's update_url." \
-                "  -s hash_url    znx's hash_url." \
-                "  -r release     znx's release."
+        ( -h | --help )     put "mkiso: Generate bootable ISO images." \
+                                "" \
+                                "Usage:" \
+                                "  mkiso [-h|--help]            Show this help." \
+                                "  mkiso [options] <dir> <img>  Generate img with contents from dir." \
+                                "" \
+                                "Options:" \
+                                "  -d, --debug    Enable debugging messages." \
+                                "  -b             Enable BIOS support." \
+                                "  -e             Enable UEFI support." \
+                                "  -V label       Use label as filesystem label." \
+                                "  -g file        Use file as a GRUB configuration file." \
+                                "  -t path        Use path as a GRUB theme." \
+                                "  -u update_url  znx's update_url." \
+                                "  -s hash_url    znx's hash_url." \
+                                "  -r release     znx's release."
             exit;;
 
-        (-*)    err "unknown option '$1'.";;
-        (*)     break;;
+        ( -* )  err "Unknown option '$1'.";;
+        ( * )   break;;
     esac
 done
 
 
-#	check the command line.
+#   Check the command line.
 
 iso_dir="$1"
 output="$2"
@@ -82,7 +58,7 @@ test -d "$iso_dir" ||
     err "'$iso_dir' is not a directory."
 
 
-#	copy the configuration files.
+#   Copy the configuration files.
 
 test "$config_files" && {
     mkdir -p "$iso_dir/boot/grub"
@@ -90,7 +66,7 @@ test "$config_files" && {
 }
 
 
-#	copy the themes.
+#   Copy the themes.
 
 test "$themes" && {
     mkdir -p "$iso_dir/boot/grub/themes"
@@ -98,29 +74,25 @@ test "$themes" && {
 }
 
 
-#	create the .INFO file if needed.
+#   Create the .INFO file.
 
-test "$hash_url" && put "HASH_URL $hash_url" >> "$iso_dir/.INFO"
-test "$update_url" && put "UPDATE_URL $update_url" >> "$iso_dir/.INFO"
-test "$release" && put "RELEASE $release" >> "$iso_dir/.INFO"
-
-
-#	GRUB2 modules.
-
-_bios_mods="biosdisk boot linux search normal configfile part_gpt btrfs ext2 fat iso9660 loopback test keystatus gfxmenu regexp probe all_video gfxterm font echo read ls cat png jpeg halt reboot"
-_uefi_mods="efi_gop efi_uga boot linux search normal configfile part_gpt btrfs ext2 fat iso9660 loopback test keystatus gfxmenu regexp probe all_video gfxterm font echo read ls cat png jpeg halt reboot"
+>> "$iso_dir/.INFO" put \
+    "HASH_URL $hash_url" \
+    "UPDATE_URL $update_url" \
+    "RELEASE $release"
 
 
-#	generate boot artifacts.
+
+
+#   Generate boot artifacts.
 
 test "$bios" = y && {
     bios_img=bios.img
 
-    grub-mkimage \
-        -O i386-pc-eltorito \
-        -o "$iso_dir/$bios_img" \
-        -p /boot/grub \
-        $_bios_mods
+    grub-mkimage -O i386-pc-eltorito \
+                 -o "$iso_dir/$bios_img" \
+                 -p /boot/grub \
+                 biosdisk boot linux search normal configfile part_gpt btrfs ext2 fat iso9660 loopback test keystatus gfxmenu regexp probe all_video gfxterm font echo read ls cat png jpeg halt reboot
 
     bios_opts="
         -eltorito-alt-boot
@@ -139,26 +111,23 @@ test "$bios" = y && {
 test "$uefi" = y && {
     efi_img=$(mktemp)
 
-    grub-mkimage \
-        -O x86_64-efi \
-        -o "$efi_img" \
-        -p /boot/grub \
-        $_uefi_mods
+    grub-mkimage -O x86_64-efi \
+                 -o "$efi_img" \
+                 -p /boot/grub \
+                 efi_gop efi_uga boot linux search normal configfile part_gpt btrfs ext2 fat iso9660 loopback test keystatus gfxmenu regexp probe all_video gfxterm font echo read ls cat png jpeg halt reboot
 
     export MTOOLS_SKIP_CHECK=1
-    mkfs.vfat \
-        -C "$iso_dir/efi.img" \
-        $(($(wc -c < $efi_img) / 1024 + 511))
 
-    mmd \
-        -i "$iso_dir/efi.img" \
+    mkfs.vfat -C "$iso_dir/efi.img" \
+              $(($(wc -c < $efi_img) / 1024 + 511))
+
+    mmd -i "$iso_dir/efi.img" \
         efi \
         efi/boot
 
-    mcopy \
-        -i "$iso_dir/efi.img" \
-        "$efi_img" \
-        ::efi/boot/bootx64.efi
+    mcopy -i "$iso_dir/efi.img" \
+          "$efi_img" \
+          ::efi/boot/bootx64.efi
 
     uefi_opts="
         -eltorito-alt-boot
@@ -170,14 +139,13 @@ test "$uefi" = y && {
 }
 
 
-#	generate ISO image.
+#   Generate ISO image.
 
-xorriso \
-    -as mkisofs \
-    -iso-level 3 \
-    -full-iso9660-filenames \
-    -volid "$label" \
-    -o "$output" \
-    "$iso_dir" \
-    $bios_opts \
-    $uefi_opts
+xorriso -as mkisofs \
+        -iso-level 3 \
+        -full-iso9660-filenames \
+        -volid "$label" \
+        -o "$output" \
+        "$iso_dir" \
+        $bios_opts \
+        $uefi_opts
diff --git a/pull b/pull
--- a/pull
+++ b/pull
@@ -1,37 +1,36 @@
 #! /bin/sh
 
 
-err () { printf "${0##*/}: \e[31mError:\e[0m %s\n" "$*" >&2; exit 1; }
-
-
 case "$1" in
-    (-h|--help)
+    ( -h | --help )
         printf "%s\n" \
-            "${0##*/}: pull an image from DockerHub into a directory." \
+            "pull: Fetch an image from DockerHub into a directory." \
             "" \
-            "usage:" \
-            "  ${0##*/} pull [-h|--help]  show this help." \
-            "  ${0##*/} pull <dir> <img>"
+            "Usage:" \
+            "  pull [-h|--help]  show this help." \
+            "  pull <dir> <img>  Fetch img into dir."
         exit;;
 esac
 
 
-#	Functions.
+#   Functions.
+
+err () { printf "${0##*/}: \e[31mError:\e[0m %s\n" "$*" >&2; exit 1; }
 
 _get_manifest () {
     curl -f -s \
-        -H "Authorization: Bearer $3" \
-        -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
-        "https://index.docker.io/v2/$1/manifests/$2"
+         -H "Authorization: Bearer $3" \
+         -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
+         "https://index.docker.io/v2/$1/manifests/$2"
 }
 
 
 _pull_layer () {
     echo "Downloading '$1'."
     curl -f -# -OL \
-        -H "Authorization: Bearer $3" \
-        -H "Accept: application/vnd.docker.image.rootfs.diff.tar.gzip" \
-        "https://index.docker.io/v2/$2/blobs/$1"
+         -H "Authorization: Bearer $3" \
+         -H "Accept: application/vnd.docker.image.rootfs.diff.tar.gzip" \
+         "https://index.docker.io/v2/$2/blobs/$1"
 }
 
 
@@ -53,7 +52,7 @@ _pull () {
 }
 
 
-#   	Process the request.
+#   Process the request.
 
 test $# -eq 2 ||
     err "wrong number of arguments."
@@ -64,14 +63,14 @@ owner="${img%%/*}"
 out="$1"
 
 test "$img" ||
-    err "no image provided."
+    err "No image provided."
 
 mkdir -p "$out"
 
 test -z "$tag" -o "$tag" = "$img" && tag=latest
 test -z "$owner" -o "$owner" = "$img" && img="library/$img"
 
-echo "trying to pull $img:$tag"
+echo "Pulling $img:$tag..."
 
 until test "$token"; do
     token=$(curl -sf "https://auth.docker.io/token?service=registry.docker.io&scope=repository:$img:pull" | jq -r .token)
diff --git a/runch b/runch
--- a/runch
+++ b/runch
@@ -1,33 +1,26 @@
 #! /bin/sh
 
 
+#   Functions.
+
 put () { printf "%b\n" "$@"; }
-err () { put "${0##*/}: \e[31merror:\e[0m $*" >&2; exit 1; }
-
-
-#	functions.
+err () { put "${0##*/}: \e[31mError:\e[m $*" >&2; exit 1; }
 
 clean () {
-    umount -Rf \
-        "$chroot_dir/proc" \
-        "$chroot_dir/sys" \
-        "$chroot_dir/dev" \
-        "$chroot_dir/run" \
-        "$chroot_dir/tmp" \
-        "$chroot_dir/etc/hosts" \
-        "$chroot_dir/etc/host.conf" \
-        "$chroot_dir/etc/nsswitch.conf" \
-        "$chroot_dir/etc/resolv.conf"
+    umount -Rf "$chroot_dir/proc" \
+               "$chroot_dir/sys" \
+               "$chroot_dir/dev" \
+               "$chroot_dir/run" \
+               "$chroot_dir/tmp" \
+               "$chroot_dir/etc/hosts" \
+               "$chroot_dir/etc/host.conf" \
+               "$chroot_dir/etc/nsswitch.conf" \
+               "$chroot_dir/etc/resolv.conf"
 
-    #	clean the user mount points.
+    #   Clean the user mount points.
 
-    for m in $_extra_mount_points; do
-        umount -Rf "$chroot_dir/${m##*:}"
-    done
-
-    for d in $_rm_f; do
-        rm -rf "$chroot_dir/$d"
-    done
+    for m in $_extra_mount_points; do umount -Rf "$chroot_dir/${m##*:}"; done
+    for d in $_rm_f; do rm -rf "$chroot_dir/$d"; done
 }
 
 
@@ -44,53 +37,41 @@ mnt () {
 }
 
 
-#	parse the command line.
+#   Parse the command line.
 
 while :; do
     case "$1" in
-        (-m)
-            _extra_mount_points="$_extra_mount_points $2"
-            shift 2;;
+        ( -m )  _extra_mount_points="$_extra_mount_points $2"; shift 2;;
+        ( -u )  user_spec="--userspec=$2"; shift 2;;
+        ( -r )  _rm_f="$_rm_f $2"; shift 2;;
 
-        (-u)
-            user_spec="--userspec=$2"
-            shift 2;;
+        ( -d | --debug )    set -x; shift;;
 
-        (-r)
-            _rm_f="$_rm_f $2"
-            shift 2;;
-
-        (-d|--debug)
-            set -x
-            shift;;
-
-        (-h|--help)
-            put \
-                "runch: run commands in a preconfigured chroot." \
-                "" \
-                "usage:" \
-                "  runch opts dir cmd args  where opts are any options, dir is the chroot directory," \
-                "                           cmd is the command to be ran, and args are any arguments" \
-                "                           to pass to the command." \
-                "" \
-                "options:" \
-                "  -h, --help       show this help." \
-                "  -d, --debug      enable debugging messges." \
-                "  -m src:mnt       mount src into <dir>/mnt." \
-                "  -u user[:group]  run cmd as the specified user and group id." \
-                "  -r file          on exit, remove file from chroot directory."
+        ( -h | --help )     put "runch: run commands in a preconfigured chroot." \
+                                "" \
+                                "usage:" \
+                                "  runch opts dir cmd args  where opts are any options, dir is the chroot directory," \
+                                "                           cmd is the command to be ran, and args are any arguments" \
+                                "                           to pass to the command." \
+                                "" \
+                                "options:" \
+                                "  -h, --help       show this help." \
+                                "  -d, --debug      enable debugging messges." \
+                                "  -m src:mnt       mount src into <dir>/mnt." \
+                                "  -u user[:group]  run cmd as the specified user and group id." \
+                                "  -r file          on exit, remove file from chroot directory."
             exit;;
 
-        (-*) err "unknown option '$1'.";;
-        (*)  break;;
+        ( -* )  err "Unknown option '$1'.";;
+        ( * )   break;;
     esac
 done
 
 
-#	check the command line.
+#   Check the command line.
 
 test $(id -u) -eq 0 ||
-    err "this program needs root privileges to run."
+    err "This program needs root privileges to run."
 
 test -d "$1" ||
     err "'$1' is not a directory."
@@ -99,19 +80,18 @@ chroot_dir="$1"
 shift
 
 
-#	clean the chroot directory on exit.
+#   Clean the chroot directory on exit.
 
 trap clean EXIT HUP INT TERM
 
 
-#	create the FHS mount points for the chroot.
+#   Create the FHS mount-points for the chroot.
 
-mkdir -p \
-    "$chroot_dir/proc" \
-    "$chroot_dir/sys" \
-    "$chroot_dir/dev" \
-    "$chroot_dir/run" \
-    "$chroot_dir/tmp"
+mkdir -p "$chroot_dir/proc" \
+         "$chroot_dir/sys" \
+         "$chroot_dir/dev" \
+         "$chroot_dir/run" \
+         "$chroot_dir/tmp"
 
 mount -t proc -o nosuid,noexec,nodev - "$chroot_dir/proc"
 mount -t sysfs -o nosuid,noexec,nodev,ro - "$chroot_dir/sys"
@@ -122,7 +102,7 @@ mount -t tmpfs -o mode=1777,strictatime,nodev,nosuid - "$chroot_dir/tmp"
 mount -B /run "$chroot_dir/run"
 
 
-#	allow network access.
+#   Allow network access.
 
 mkdir -p "$chroot_dir/etc"
 
@@ -139,13 +119,11 @@ do
 done
 
 
-#	mount user-specified mount points.
+#   Mount user-specified mount-points.
 
-for dir in $_extra_mount_points; do
-    mnt "${dir%%:*}" "$chroot_dir/${dir##*:}"
-done
+for dir in $_extra_mount_points; do mnt "${dir%%:*}" "$chroot_dir/${dir##*:}"; done
 
 
-#	run the chroot.
+#   chroot.
 
 chroot ${user_spec:+"$user_spec"} -- "$chroot_dir" "$@"
diff --git a/synth b/synth
--- a/synth
+++ b/synth
@@ -1,28 +1,28 @@
 #! /bin/sh
 
 
-put () { printf "%b\n" "$@"; }
-err () { put "${0##*/}: \e[31merror:\e[0m $*" >&2; exit 1; }
-
 case "$1" in
-    (-h|--help)
+    ( -h | --help )
         put "synth: generate the ISO image described in the given file." \
             "" \
-            "usage:" \
+            "Usage:" \
             "  synth opts  where opts is any option." \
             "  synth args  where args are the arguments." \
             "" \
-            "options:" \
+            "Options:" \
             "  -h,--help   show this help." \
             "" \
-            "arguments:" \
+            "Arguments:" \
             "  file img    given file as input, generate img ISO image." \
             "              img is optional. if not passed, it will be derived from file."
         exit;;
 esac
 
 
-#	functions.
+#   Functions.
+
+put () { printf "%b\n" "$@"; }
+err () { put "${0##*/}: \e[31mError:\e[0m $*" >&2; exit 1; }
 
 get_k () { put "$desc" | grep "$1" | cut -d " " -f 2-; }
 
@@ -31,15 +31,13 @@ setup_base () {
     sys_base=$(get_k BASE)
 
     case "$sys_base" in
-        (@URL:*)
-            tmp=$(mktemp)
-            wget -qO $tmp "${sys_base#@URL:}"
-            tar xf "$tmp" -C "$tmp_root";;
+        ( @URL:* )      tmp=$(mktemp)
+                        wget -qO $tmp "${sys_base#@URL:}"
+                        tar xf "$tmp" -C "$tmp_root";;
 
-        (@LOCAL:*)
-            tar xf "${sys_base#@LOCAL:}" -C "$tmp_root";;
+        ( @LOCAL:* )    tar xf "${sys_base#@LOCAL:}" -C "$tmp_root";;
 
-        (*)  pull "$tmp_root" "$sys_base";;
+        ( * )           pull "$tmp_root" "$sys_base";;
     esac
 
     test -x "${input%/*}/preinst" ||
@@ -56,24 +54,24 @@ install_pkgs () {
     pkgs=$(get_k PACKAGES)
 
     case "$pm" in
-        (pacman)
+        ( pacman )
             pm_u="$pm --noconfirm -Syu"
             pm_i="$pm --noconfirm -S";;
 
-        (apt)
+        ( apt )
             pm_u="$pm -y upgrade"
             pm_i="$pm -y install";;
 
-        (apk)
+        ( apk )
             pm_u="$pm update"
             pm_i="$pm add";;
 
-        ("")
+        ( "" )
             put " :: warning:" \
                 "    no package manager specified."
             return;;
 
-        (*)  err "unsupported package manager '$pm'. aborting.";;
+        ( * )  err "unsupported package manager '$pm'. aborting.";;
     esac
 
     runch $tmp_root $pm_u
@@ -113,7 +111,7 @@ setup_bootloader () {
 }
 
 
-#	setup the build.
+#   Start the build.
 
 root_sfs=rootfs.sfs
 tmp_root=$(mktemp -d $(pwd)/.tmp.XXXX)
@@ -122,11 +120,6 @@ iso_dir=$(mktemp -d $(pwd)/.tmp.XXXX)
 input="${1:-synthfile}"
 output="${2:-img.iso}"
 
-
-#	remove waste after the build.
-
-trap "rm -rf '$tmp_root' '$iso_dir'" EXIT HUP INT TERM
-
 test -f "$input" ||
     err "'$input' is not a file."
 
@@ -134,7 +127,9 @@ test -e "$output" &&
     err "'$output' already exists."
 
 
-#	start the build.
+#   Remove waste after the build.
+
+trap "rm -rf '$tmp_root' '$iso_dir'" EXIT HUP INT TERM
 
 desc=$(
     sed -E \
@@ -152,33 +147,29 @@ install_pkgs
 setup_bootloader
 
 
-#	all done. generate the artifacts.
+#   All done. Generate the artifacts.
 
-mksquashfs \
-    $tmp_root \
-    $iso_dir/$root_sfs \
-    -b 1M \
-    -comp xz \
-    -no-progress
-
-
-mkiso \
-    -u "$(get_k UPDATE_URL)" \
-    -s "$(get_k HASH_URL)" \
-    -r "$(get_k RELEASE)" \
-    $(test $(get_k BIOS_BOOT) = on && put "-b") \
-    $(test $(get_k UEFI_BOOT) = on && put "-e") \
-    "$iso_dir" \
-    "$output"
+mksquashfs $tmp_root \
+           $iso_dir/$root_sfs \
+           -b 1M \
+           -comp xz \
+           -no-progress
 
 
-zsyncmake \
-    "$output" \
-    -u "$(get_k UPDATE_URL)" \
-    -o "$output.zsync"
+mkiso -u "$(get_k UPDATE_URL)" \
+      -s "$(get_k HASH_URL)" \
+      -r "$(get_k RELEASE)" \
+      $(test $(get_k BIOS_BOOT) = on && put "-b") \
+      $(test $(get_k UEFI_BOOT) = on && put "-e") \
+      "$iso_dir" \
+      "$output"
+
+
+zsyncmake "$output" \
+          -u "$(get_k UPDATE_URL)" \
+          -o "$output.zsync"
 
 
 sha256sum "$output" > "$output.sha256sum"
-md5sum "$output" > "$output.md5sum"
 
 put "$output"*
