updates, updates...

diff --git a/runch b/runch
--- a/runch
+++ b/runch
@@ -1,36 +1,37 @@
 #! /bin/sh
 
 
-err () { printf "${0##*/}: \e[31mError:\e[0m %s\n" "$*" >&2; exit 1; }
+put () { printf "%b\n" "$@"; }
+err () { put "${0##*/}: \e[31merror:\e[0m $*" >&2; exit 1; }
 
 
 #	functions.
 
 clean () {
-	umount -R -f \
-		$chroot_dir/proc \
-		$chroot_dir/sys \
-		$chroot_dir/dev \
-		$chroot_dir/run \
-		$chroot_dir/tmp \
-		$chroot_dir/etc/hosts \
-		$chroot_dir/etc/host.conf \
-		$chroot_dir/etc/nsswitch.conf \
-		$chroot_dir/etc/resolv.conf
+	umount -Rf \
+		"$chroot_dir/proc" \
+		"$chroot_dir/sys" \
+		"$chroot_dir/dev" \
+		"$chroot_dir/run" \
+		"$chroot_dir/tmp" \
+		"$chroot_dir/etc/hosts" \
+		"$chroot_dir/etc/host.conf" \
+		"$chroot_dir/etc/nsswitch.conf" \
+		"$chroot_dir/etc/resolv.conf"
 
 	#	clean the user mount points.
 
 	for m in $_extra_mount_points; do
-		umount -R -f $chroot_dir/"${m##*:}"
+		umount -Rf "$chroot_dir/${m##*:}"
 	done
 
 	for d in $_rm_f; do
-		rm -rf $chroot_dir/"$d"
+		rm -rf "$chroot_dir/$d"
 	done
 }
 
 
-_mount () {
+mnt () {
 	test -e "$1" ||
 		err "'$1' does not exist."
 
@@ -68,21 +69,23 @@ while :; do
 		;;
 
 		-h|--help)
-			printf "%s\n" \
-				"${0##*/}: run commands in a preconfigured chroot." \
+			put \
+				"runch: run commands in a preconfigured chroot." \
 				"" \
 				"usage:" \
-				"  ${0##*/} [-h|--help]  show this help." \
-				"  ${0##*/} [options] <dir> <cmd> [args]" \
+				"  runch opts dir cmd args  where opts are any options, dir is the chroot directory," \
+				"                           cmd is the command to be ran, and args are any arguments" \
+				"                           to pass to the command." \
 				"" \
 				"options:" \
-				"  -u user[:group]  run <cmd> as the specified user and group id." \
-				"  -m src:mnt       mount src into <dir>/mnt." \
-				"  -r file          remove file from <dir> when <cmd> finishes."
+				"  -h,--help                show this help." \
+				"  -u user[:group]          run cmd as the specified user and group id." \
+				"  -m src:mnt               mount src into <dir>/mnt." \
+				"  -r file                  on exit, remove file from chroot directory."
 			exit
 		;;
 
-		-*) err "Unknown option '$1'.";;
+		-*) err "unknown option '$1'.";;
 		*) break;;
 	esac
 done
@@ -91,7 +94,7 @@ done
 #	check the command line.
 
 test $(id -u) -eq 0 ||
-	err "This program needs root privileges to run."
+	err "this program needs root privileges to run."
 
 test -d "$1" ||
 	err "'$1' is not a directory."
@@ -108,34 +111,34 @@ trap clean EXIT HUP INT TERM
 #	create the FHS mount points for the chroot.
 
 mkdir -p \
-	$chroot_dir/proc \
-	$chroot_dir/sys \
-	$chroot_dir/dev \
-	$chroot_dir/run \
-	$chroot_dir/tmp
+	"$chroot_dir/proc" \
+	"$chroot_dir/sys" \
+	"$chroot_dir/dev" \
+	"$chroot_dir/run" \
+	"$chroot_dir/tmp"
 
-mount -t proc -o nosuid,noexec,nodev - $chroot_dir/proc
-mount -t sysfs -o nosuid,noexec,nodev,ro - $chroot_dir/sys
-mount -t devtmpfs -o mode=0755,nosuid - $chroot_dir/dev
-mount -t devpts -o mode=0620,gid=5,nosuid,noexec - $chroot_dir/dev/pts
-mount -t tmpfs -t tmpfs -o mode=1777,nosuid,nodev - $chroot_dir/dev/shm
-mount -t tmpfs -o mode=1777,strictatime,nodev,nosuid - $chroot_dir/tmp
-mount -B /run $chroot_dir/run
+mount -t proc -o nosuid,noexec,nodev - "$chroot_dir/proc"
+mount -t sysfs -o nosuid,noexec,nodev,ro - "$chroot_dir/sys"
+mount -t devtmpfs -o mode=0755,nosuid - "$chroot_dir/dev"
+mount -t devpts -o mode=0620,gid=5,nosuid,noexec - "$chroot_dir/dev/pts"
+mount -t tmpfs -t tmpfs -o mode=1777,nosuid,nodev - "$chroot_dir/dev/shm"
+mount -t tmpfs -o mode=1777,strictatime,nodev,nosuid - "$chroot_dir/tmp"
+mount -B /run "$chroot_dir/run"
 
 
 #	allow network access.
 
-mkdir -p $chroot_dir/etc
+mkdir -p "$chroot_dir/etc"
 
 for f in \
-	/etc/hosts \
-	/etc/host.conf \
-	/etc/nsswitch.conf \
-	/etc/resolv.conf
+	"/etc/hosts" \
+	"/etc/host.conf" \
+	"/etc/nsswitch.conf" \
+	"/etc/resolv.conf"
 do
-	test -f $f && {
-		>> $chroot_dir/$f
-		mount -B $f $chroot_dir/$f
+	test -f "$f" && {
+		>> "$chroot_dir/$f"
+		mount -B "$f" "$chroot_dir/$f"
 	}
 done
 
@@ -143,10 +146,10 @@ done
 #	mount user-specified mount points.
 
 for dir in $_extra_mount_points; do
-	_mount "${dir%%:*}" $chroot_dir/"${dir##*:}"
+	mnt "${dir%%:*}" "$chroot_dir/${dir##*:}"
 done
 
 
 #	run the chroot.
 
-chroot $user_spec "$chroot_dir" "$@"
+chroot "$user_spec" "$chroot_dir" "$@"
diff --git a/synth b/synth
--- a/synth
+++ b/synth
@@ -1,17 +1,24 @@
 #! /bin/sh
 
 
-set -e
-err () { printf "${0##*/}: \e[31mError:\e[0m %s\n" "$*" >&2; exit 1; }
+put () { printf "%b\n" "$@"; }
+err () { put "${0##*/}: \e[31merror:\e[0m $*" >&2; exit 1; }
 
 case "$1" in
 	-h|--help)
-		printf "%s\n" \
-			"${0##*/}: generate the ISO image described in the given file." \
+		put \
+			"synth: generate the ISO image described in the given file." \
 			"" \
 			"usage:" \
-			"  ${0##*/} [-h|--help]  show this help." \
-			"  ${0##*/} <file> [img]"
+			"  synth opts  where opts is any option." \
+			"  synth args  where args are the arguments." \
+			"" \
+			"options:" \
+			"  -h,--help   show this help." \
+			"" \
+			"arguments:" \
+			"  file img    given file as input, generate img ISO image." \
+			"              img is optional. if not passed, it will be derived from file."
 		exit
 	;;
 esac
@@ -19,7 +26,7 @@ esac
 
 #	functions.
 
-get_k () { echo "$desc" | grep "$1" | cut -d " " -f 2-; }
+get_k () { put "$desc" | grep "$1" | cut -d " " -f 2-; }
 
 
 setup_base () {
@@ -29,18 +36,18 @@ setup_base () {
 		@URL:*)
 			tmp=$(mktemp)
 			wget -qO $tmp "${sys_base#@URL:}"
-			tar xf $tmp -C $tmp_root
+			tar xf "$tmp" -C "$tmp_root"
 		;;
 
-		@LOCAL:*) tar xf "${sys_base#@LOCAL:}" -C $tmp_root;;
-		*) pull $tmp_root $sys_base;;
+		@LOCAL:*) tar xf "${sys_base#@LOCAL:}" -C "$tmp_root";;
+		*) pull "$tmp_root" "$sys_base";;
 	esac
 
 	test -x "${input%/*}/prepare.sh" || return
 
-	cp "${input%/*}/prepare.sh" $tmp_root
-	runch $tmp_root /prepare.sh
-	rm -rf $tmp_root/prepare.sh
+	cp "${input%/*}/prepare.sh" "$tmp_root"
+	runch "$tmp_root" "/prepare.sh"
+	rm -rf "$tmp_root/prepare.sh"
 }
 
 
@@ -65,13 +72,13 @@ install_pkgs () {
 		;;
 
 		"")
-			printf "%s\n" \
+			put \
 				" :: warning:" \
 				"    no package manager specified."
 			return
 		;;
 
-		?*) err "unsupported package manager '$pm'. aborting.";;
+		*) err "unsupported package manager '$pm'. aborting.";;
 	esac
 
 	runch $tmp_root $pm_u
@@ -83,13 +90,13 @@ install_pkgs () {
 		return
 	}
 
-	runch $tmp_root $pm_i $pkgs
+	runch "$tmp_root" $pm_i $pkgs
 
 	test -x "${input%/*}/finish.sh" &&
 		runch \
-			-m "${input%/*}/finish.sh":/finish.sh  \
-			-r /finish.sh \
-			$tmp_root /finish.sh
+			-m "${input%/*}/finish.sh:/finish.sh"  \
+			-r "/finish.sh" \
+			"$tmp_root" "/finish.sh"
 }
 
 
@@ -121,7 +128,7 @@ output="${2:-${1%.synth}.iso}"
 
 #	remove waste after the build.
 
-trap "rm -rf $tmp_root $iso_dir" EXIT HUP INT TERM
+trap "rm -rf '$tmp_root' '$iso_dir'" EXIT HUP INT TERM
 
 test -f "$input" ||
 	err "'$input' is not a file."
@@ -162,9 +169,9 @@ mkiso \
 	-u "$(get_k UPDATE_URL)" \
 	-s "$(get_k HASH_URL)" \
 	-r "$(get_k RELEASE)" \
-	$(test $(get_k BIOS_BOOT) = on && echo "-b") \
-	$(test $(get_k UEFI_BOOT) = on && echo "-e") \
-	$iso_dir \
+	$(test $(get_k BIOS_BOOT) = on && put "-b") \
+	$(test $(get_k UEFI_BOOT) = on && put "-e") \
+	"$iso_dir" \
 	"$output"
 
 
@@ -177,9 +184,4 @@ zsyncmake \
 sha256sum "$output" > "$output.sha256sum"
 md5sum "$output" > "$output.md5sum"
 
-printf "%s\n" \
-	"successfully generated '$output'." \
-	"---------------------------------" \
-	""
-
-ls --color -l $output*
+put "$output"*
