Normalize messages.

diff --git a/synth b/synth
--- a/synth
+++ b/synth
@@ -3,18 +3,18 @@
 
 case "$1" in
     ( -h | --help )
-        put "synth: generate the ISO image described in the given file." \
+        put "synth: Generate the ISO image described in the given file." \
             "" \
             "Usage:" \
-            "  synth opts  where opts is any option." \
-            "  synth args  where args are the arguments." \
+            "  synth opts  Where opts is any option." \
+            "  synth args  Where args are the arguments." \
             "" \
             "Options:" \
-            "  -h,--help   show this help." \
+            "  -h,--help   Show this help." \
             "" \
             "Arguments:" \
-            "  file img    given file as input, generate img ISO image." \
-            "              img is optional. if not passed, it will be derived from file."
+            "  file img    Given file as input, generate the ISO image img." \
+            "              img is optional. If not passed, it will be named after file."
         exit;;
 esac
 
@@ -22,7 +22,7 @@ esac
 #   Functions.
 
 put () { printf "%b\n" "$@"; }
-err () { put "${0##*/}: \e[31mError:\e[0m $*" >&2; exit 1; }
+err () { put "synth: \e[31mError:\e[0m $*" >&2; exit 1; }
 
 get_k () { put "$desc" | grep "$1" | cut -d " " -f 2-; }
 
@@ -67,19 +67,16 @@ install_pkgs () {
             pm_i="$pm add";;
 
         ( "" )
-            put " :: warning:" \
-                "    no package manager specified."
+            put " :: Warning: No package manager specified."
             return;;
 
-        ( * )  err "unsupported package manager '$pm'. aborting.";;
+        ( * )  err "Unsupported package manager '$pm'. Aborting.";;
     esac
 
     runch $tmp_root $pm_u
 
     test "$pkgs" || {
-        printf "%s\n" \
-            " :: warning:" \
-            "    no additional packages were specified."
+        put " :: Warning: No additional packages were specified."
         return
     }
 
@@ -123,9 +120,6 @@ output="${2:-img.iso}"
 test -f "$input" ||
     err "'$input' is not a file."
 
-test -e "$output" &&
-    err "'$output' already exists."
-
 
 #   Remove waste after the build.
 
@@ -149,8 +143,8 @@ setup_bootloader
 
 #   All done. Generate the artifacts.
 
-mksquashfs $tmp_root \
-           $iso_dir/$root_sfs \
+mksquashfs "$tmp_root" \
+           "$iso_dir/$root_sfs" \
            -b 1M \
            -comp xz \
            -no-progress
